import { NextRequest } from "next/server";
import { z } from "zod";
import { nanoid } from "nanoid";
import { requireUser, maybeRequireAppCheck, GuardError } from "@/lib/auth/guard";
import { checkChatLimits, checkFluxLimit } from "@/lib/ratelimit";
import { getModel } from "@/lib/models/registry";
import { nimImageGenerate, NimError } from "@/lib/nim/client";
import { getAdminStorage } from "@/lib/firebase/admin";
import { ensureUser, persistAssistantMessage, persistUserMessage, createChat, getChat } from "@/lib/firebase/firestore";
import { generatedImagePath } from "@/lib/storage/paths";
import type { ChatMessage } from "@/lib/types";

export const runtime = "nodejs";
export const maxDuration = 120;
export const dynamic = "force-dynamic";

const Body = z.object({
  chatId: z.string().optional().nullable(),
  modelId: z.string(),
  prompt: z.string().min(1).max(4_000),
  referenceImageStoragePath: z.string().optional(),
  steps: z.number().int().min(1).max(50).optional(),
  cfgScale: z.number().min(0).max(20).optional(),
  aspectRatio: z.string().optional(),
  seed: z.number().int().optional(),
});

export async function POST(req: NextRequest) {
  let user;
  try {
    user = await requireUser(req);
    await maybeRequireAppCheck(req);
  } catch (e) {
    if (e instanceof GuardError) return e.toResponse();
    throw e;
  }

  const flux = await checkFluxLimit(user.uid);
  if (!flux.ok) return Response.json({ error: "rate_limited", scope: "flux", retryAfter: flux.retryAfter }, { status: 429 });
  const lim = await checkChatLimits(user.uid);
  if (!lim.ok) return Response.json({ error: "rate_limited", scope: lim.scope, retryAfter: lim.retryAfter }, { status: 429 });

  let body: z.infer<typeof Body>;
  try {
    body = Body.parse(await req.json());
  } catch (e) {
    return Response.json({ error: "invalid_body", detail: String(e) }, { status: 400 });
  }

  const model = getModel(body.modelId);
  if (!model || model.endpoint !== "infer") {
    return Response.json({ error: "unknown_model" }, { status: 400 });
  }

  await ensureUser(user.uid, { email: user.email, displayName: user.name, photoUrl: user.picture });

  let chatId = body.chatId && body.chatId !== "new" ? body.chatId : null;
  if (chatId) {
    const existing = await getChat(chatId);
    if (!existing) chatId = null;
    else if (existing.ownerId !== user.uid) {
      return Response.json({ error: "forbidden" }, { status: 403 });
    }
  }
  if (!chatId) chatId = await createChat(user.uid, model.id, body.prompt.slice(0, 60) || "New image");

  const userMessageId = nanoid(12);
  const assistantMessageId = nanoid(12);

  // Persist the user prompt as a message with text part.
  await persistUserMessage({
    chatId,
    uid: user.uid,
    message: {
      id: userMessageId,
      role: "user",
      parts: [{ type: "text", text: body.prompt }],
      createdAt: Date.now(),
    },
  });

  // Optional reference image (Kontext).
  let referenceImage: string | undefined;
  if (body.referenceImageStoragePath) {
    referenceImage = await downloadAsBase64(body.referenceImageStoragePath);
  }

  let result;
  try {
    result = await nimImageGenerate({
      model: model.id,
      prompt: body.prompt,
      image: referenceImage,
      steps: body.steps,
      cfg_scale: body.cfgScale,
      aspect_ratio: body.aspectRatio,
      seed: body.seed,
    });
  } catch (e) {
    const msg = e instanceof NimError ? `${e.status}: ${e.body.slice(0, 200)}` : (e as Error).message;
    return Response.json({ error: "generation_failed", message: msg }, { status: 502 });
  }

  // Upload the PNG to Firebase Storage.
  const buffer = Buffer.from(result.base64, "base64");
  const path = generatedImagePath(user.uid, chatId, assistantMessageId);
  const file = getAdminStorage().bucket().file(path);
  await file.save(buffer, {
    metadata: { contentType: "image/png", cacheControl: "public, max-age=31536000" },
    resumable: false,
  });
  const [downloadUrl] = await file.getSignedUrl({
    action: "read",
    expires: Date.now() + 7 * 24 * 60 * 60 * 1000, // 7 days
  });

  const assistantMessage: ChatMessage = {
    id: assistantMessageId,
    role: "assistant",
    parts: [
      {
        type: "image",
        storagePath: path,
        downloadUrl,
        mimeType: "image/png",
        fileName: `${assistantMessageId}.png`,
      },
      { type: "text", text: `Generated by ${model.displayName}.` },
    ],
    model: model.id,
    thinkingMode: null,
    usage: null,
    finishReason: "stop",
    createdAt: Date.now() + 1,
  };

  await persistAssistantMessage({
    chatId,
    uid: user.uid,
    message: assistantMessage,
    artifacts: [],
    modelId: model.id,
    isFirstTurn: true,
    newTitle: body.prompt.slice(0, 60) || undefined,
  });

  return Response.json({
    chatId,
    userMessageId,
    assistantMessageId,
    imageUrl: downloadUrl,
    storagePath: path,
    seed: result.seed,
    licenseCommercial: model.licenseCommercial,
  });
}

async function downloadAsBase64(storagePath: string): Promise<string> {
  const path = storagePath.replace(/^gs:\/\/[^/]+\//, "");
  const [buffer] = await getAdminStorage().bucket().file(path).download();
  // Heuristic: detect mime from magic bytes; default png.
  const header = buffer.subarray(0, 4);
  let mime = "image/png";
  if (header[0] === 0xff && header[1] === 0xd8) mime = "image/jpeg";
  return `data:${mime};base64,${buffer.toString("base64")}`;
}
